language: java
sudo: true
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: BBLQmsEBbRo+3BQHMSDgs4BtjNkYViUy1eEj6h2zjBh8N680OejGXxu4XtgQ5eiaeTqA4V7nmyBdlBDpX4CK/IHI146s2Uwh/hUNGoZ/Hs58cVYZD+lesmpLYEaOLUAf4EdFkh2v72sc1npUaOrXMVvf/UB/fGqV+q/5K9l2qnbvvBUARiMwCNQVurmQKCIs4NCcB0U3xbMLoiZ/fOoTy04x8rtTZ1ZTQYAHpgTYfhL4xYpZsSaRCVdZDG431h6cpa5PMoMLZLUEhZRjpFFiG32RASlm1hbNvfkbaHn0Jyzc/p4nF0x+9kzUFs+VCAnHPmqtm/dT8jjvaTOgJs2ouZfp7448OJ2tVmKg22RS6x8WglG80jZKzkWqeR3KUnmejNCi0w1h+Sp2AttSWBSPGhuP+oboJwK6tZuuJpJLqtgDMxNKGTQuv5ACESFM98qZTHg8HAwhyhRjJfcLjU4ZR7s65npFwrHtOmFi51BmhTU0/SHe2zi6daXB6AbJfwYKdLT2Qg/slY3gG+n4pZkrENKY37bKW37yhPUxjOugxG2GYnV/YTApre0KkNuKEzU3Z10XBpvCmEBGszNOgUnLL13cbz8Bj11qvY1aPQ7YX+k89bEjA/HL10c0NmaO4S/4ZMbn6fwZoMCozkxkjKDZTlWTzBT/reQ8cPPVSDXD+p0=
  - secure: Qzc1arCM7oWoIj49bM/JTaR923IAuEF6DTIFX+/BqHMSY355ZqTKrGqbNroHapxMc6WwSLt9YpaYox+kDB/deze/lziRe5gUKRiAtkX3HfQt3GDIneArLEkCt74ESII8VMAKUrnobY1PxT2qj8N7tjHjfp7nG0XfyUWrT+KEkShJ7dQvN2DTBAaEtJC6LSudzdD0+ix8TiVqYm+y68wOWVWNzTwRb5EWUE3iKfzX39MH+ngFzP/PFI936rvYzL28DpFVRpC6U2DjRu4AmvDvjbKV9UIBlOo/lv5YjgTLbxm1kiw0eYpiigsuqsqZB02DEgNJAuOWuEfWzQNV/RZRJ7ZHeqbzgNklupiwHX07GZ/aL4ilMQr0MCOaSicCJ4YiCYMPcksazq3Xo6J5Kf63rM5tGiiYOQ6EsczW+WMRvF/GO2os8OZwZIXnjah/g8yBVCKzklj0Zm9w3lA/YQ7/jyDB0YzGXPXKKKLMdBiJa/ujPCZGUtrdi/2Cl4rcE8eldnx1mB1JSKdCfs2hDfQeDrKX+IYVAKH8Os4QT81+HqYibdl7Y7kTKBOecPk5djWqGpnDQ8hZZrE5iND6rBLpuH7QlzUBmpPSvCfwH0a2nbFvv450P4uqzHNFzE82RJxHcm8IJM/4y6aRBGr0LBoKIOKTLVqm5x02e8QIKfg3uqc=
  - secure: S3ZV9+Cs4Ws07Kn84n/2AChc4a1+5rF3ubXNmawQKBYv+ge+c8+mHEqyzQLeHEBQm+pRVbw0byqKIDD+9qvF+K2vTpFZQTfv2mOZJ0R4csnWiVvzY7NNyFMeGzDTQy6G2BIgW9KoCtfWf4YDq2Luo478HNfULYx0KZLpjK1NsLfHgNTJPoXRN/rcxv5rsjlfRF3a4ltjFFQBaYqwtxx4UQOV3YdLBWfMkTLBAdOYtinZ8w1FLwvV0CpdRNSGl8WY5b7NJiRSWotFXfrYgfoQGN3cn6RfQFTK6Bg+qopoK2Ma4IQDaDnvlTSoq+U3gEMjePV+/9oDAeTPG4pvJlQzq1+bnMR6ohjlG7LIptYCSIGj6KxF4MGvUrIjuPb8yz69eIq3gXZDTZHCMWvgif8n268zrF5a2w7WXcb9bILd/YFY47Iw8Od8ydZQIDMuh5X+jYKIyHs91YCL7ZZ5cLlYhRyNbthEZBevWg95zLpkdzOCaTEILmayyM1JaMo7dSiCzWf7/c6pJd3u9AIl3jYIgHVIuDKvVhRoI3uFV5yFGQ/Vbu4nG+nPP9Ir/Pj40lX11C+5M13LkNTuWmgi/ZmhSbThj5sy7whtzLTiSrx3rYzreuIBc6DCmu/qoi5tw43rBLPyMxKkFOMgTD7ZvEpdNPfFL/bePn3xw5jULy6l1kE=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
