language: java
sudo: true
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: BBLQmsEBbRo+3BQHMSDgs4BtjNkYViUy1eEj6h2zjBh8N680OejGXxu4XtgQ5eiaeTqA4V7nmyBdlBDpX4CK/IHI146s2Uwh/hUNGoZ/Hs58cVYZD+lesmpLYEaOLUAf4EdFkh2v72sc1npUaOrXMVvf/UB/fGqV+q/5K9l2qnbvvBUARiMwCNQVurmQKCIs4NCcB0U3xbMLoiZ/fOoTy04x8rtTZ1ZTQYAHpgTYfhL4xYpZsSaRCVdZDG431h6cpa5PMoMLZLUEhZRjpFFiG32RASlm1hbNvfkbaHn0Jyzc/p4nF0x+9kzUFs+VCAnHPmqtm/dT8jjvaTOgJs2ouZfp7448OJ2tVmKg22RS6x8WglG80jZKzkWqeR3KUnmejNCi0w1h+Sp2AttSWBSPGhuP+oboJwK6tZuuJpJLqtgDMxNKGTQuv5ACESFM98qZTHg8HAwhyhRjJfcLjU4ZR7s65npFwrHtOmFi51BmhTU0/SHe2zi6daXB6AbJfwYKdLT2Qg/slY3gG+n4pZkrENKY37bKW37yhPUxjOugxG2GYnV/YTApre0KkNuKEzU3Z10XBpvCmEBGszNOgUnLL13cbz8Bj11qvY1aPQ7YX+k89bEjA/HL10c0NmaO4S/4ZMbn6fwZoMCozkxkjKDZTlWTzBT/reQ8cPPVSDXD+p0=
  - secure: Qzc1arCM7oWoIj49bM/JTaR923IAuEF6DTIFX+/BqHMSY355ZqTKrGqbNroHapxMc6WwSLt9YpaYox+kDB/deze/lziRe5gUKRiAtkX3HfQt3GDIneArLEkCt74ESII8VMAKUrnobY1PxT2qj8N7tjHjfp7nG0XfyUWrT+KEkShJ7dQvN2DTBAaEtJC6LSudzdD0+ix8TiVqYm+y68wOWVWNzTwRb5EWUE3iKfzX39MH+ngFzP/PFI936rvYzL28DpFVRpC6U2DjRu4AmvDvjbKV9UIBlOo/lv5YjgTLbxm1kiw0eYpiigsuqsqZB02DEgNJAuOWuEfWzQNV/RZRJ7ZHeqbzgNklupiwHX07GZ/aL4ilMQr0MCOaSicCJ4YiCYMPcksazq3Xo6J5Kf63rM5tGiiYOQ6EsczW+WMRvF/GO2os8OZwZIXnjah/g8yBVCKzklj0Zm9w3lA/YQ7/jyDB0YzGXPXKKKLMdBiJa/ujPCZGUtrdi/2Cl4rcE8eldnx1mB1JSKdCfs2hDfQeDrKX+IYVAKH8Os4QT81+HqYibdl7Y7kTKBOecPk5djWqGpnDQ8hZZrE5iND6rBLpuH7QlzUBmpPSvCfwH0a2nbFvv450P4uqzHNFzE82RJxHcm8IJM/4y6aRBGr0LBoKIOKTLVqm5x02e8QIKfg3uqc=
  - secure: NtWDMB2lPZbnLvAdhGgZSFEiDpMEweMa3ZWME9xx0Odf6Dxogz8tzBtr1ETSkzkfBb2uwJcVCjpl43SoKrk2XsUdvo7K/DfJxakgmowHCghLFVu4wRtNkTj6f2zCCfL3KvBktyLa3BO8SA1hpMa/QyavNRh5ShCA/WjcP/8PtEPzr3TnqF55i3sgPt7+hjOdCW7W0mo6ct5tQHQBwsYo3hUkUtsEy9dCuDaLs/McBtn62Rexj3DFwjpFEW2EB8lHVj5Wt+9ZqKQwPyQ1HIvTaWv7qs0wd5gv8j0Q6HHYjp7WzLQpV5EgL53MN40KJKnDWS1yqZ8wOHdXaI0CQwJe5blvQLmGPd21Xv7WVnm2M/SHT4OUU4n5GKxuDSOaaO9eVM4rCqrxYV4XLUa+L9uichC8zOmLjcIJY4GHYDWS9yRf06vM+U5TH5igSYsj+ixZiVAZmQC/RmDTYhrxAc146LfgfeEiy7U+w5vHIYjg4+8AvCEaAuhaG7reWxRP61Ye+vVvk2eiBt6gT15jv56WfJEtt0FX9Ye6RSpI+WxUe6CAFvYBdsoFvKO4C1qTDujnzRNJ6UvvwOS/U+qBDuxnqiaGcUAbI9FM1Li+HWos+ean1cI4jhR0sglpKmLMuy8d7W4yKo/2ar8VuUfmRnmZtOC3ysbRDVXLVUjNQbup0O0=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
